# Generated by Django 3.2.3 on 2021-05-16 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_rename_books_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='note',
            field=models.TextField(default='none'),
        ),
    ]
