# Generated by Django 3.2.3 on 2021-05-16 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0003_author_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='note',
            new_name='notes',
        ),
    ]
